import { test as base, expect } from '@playwright/test'

const test = base.extend<{ checkRequests: void }>({
  checkRequests: [async ({ page }, use) => {
    const invalid: string[] = [], errors: string[] = []
    page.on('request', r => {
      if (!['http:', 'https:'].includes(new URL(r.url()).protocol)) return
      if (new URL(r.url()).origin !== 'http://127.0.0.1:4181' || !['GET', 'HEAD'].includes(r.method())) invalid.push(`${r.method()} ${r.url()}`)
    })
    page.on('pageerror', error => errors.push(error.message))
    await use()
    expect(invalid, '外部通信・書き込みAPIを使わない').toEqual([])
    expect(errors, 'ブラウザ内の例外がない').toEqual([])
  }, { auto: true }],
})

test('打刻カード・キーボード・ローカル保存', async ({ page }, info) => {
  await page.goto('/'); await page.evaluate(() => document.fonts.ready)
  await page.evaluate(() => Promise.allSettled(document.getAnimations().map(animation => animation.finished)))
  await expect(page.locator('.home-period:visible .month')).toHaveText('2026年9月')
  await expect(page.locator('.home-period:visible .home-day')).toHaveText('22日 火曜日')
  await page.screenshot({ path: info.outputPath('home.png'), fullPage: true })
  const front = page.locator('.flip-face:not(.ura)'), back = page.locator('.ura')
  const height = await page.locator('.flip-inner').evaluate(el => el.getBoundingClientRect().height)
  expect(height).toBe(160)
  const geometry = () => front.locator('.now').evaluate(el => {
    const card = el.getBoundingClientRect()
    return { height:card.height, date:el.querySelector('.home-period')!.getBoundingClientRect().top-card.top,
      action:el.querySelector('.mid')!.getBoundingClientRect().top-card.top }
  })
  const before = await geometry()
  await expect(page.locator('.flip-label')).toHaveText('足あと')
  await page.getByRole('button', { name: '今月の足あと（働いた日と稼ぎ）を見る' }).focus(); await page.keyboard.press('Enter')
  await expect(back).toBeVisible(); await expect(back).not.toHaveAttribute('inert')
  await expect(back.locator('[data-yen]')).toHaveText('¥262,000')
  await expect(back.locator('.home-period')).toBeVisible()
  await expect(back.locator('.cal i.unworked')).toHaveCount(16)
  await expect(back.locator('.stack-value')).not.toContainText('日ぶん')
  await back.locator('.home-day').click(); await expect(back).toBeVisible()
  await expect(front).toBeHidden()
  expect(await page.locator('.flip-inner').evaluate(el => el.getBoundingClientRect().height)).toBeCloseTo(height, 0)
  await page.screenshot({ path: info.outputPath('card-back.png'), fullPage: true })
  await page.keyboard.press('Enter'); await expect(front).not.toHaveAttribute('inert')
  await page.getByRole('button', { name: '出勤', exact: true }).click()
  await expect(page.locator('.home-clock .live')).toBeVisible()
  expect(await geometry()).toEqual(before)
  await page.screenshot({ path: info.outputPath('home-working.png'), fullPage:true })
  await expect(page.locator('.home-period:visible .month')).toHaveText('2026年9月')
  await page.reload(); await expect(page.locator('.home-clock .live')).toBeVisible()
  await page.getByRole('button', { name: '退勤', exact: true }).click()
  await page.getByLabel('退勤時刻').fill('18:00')
  await page.getByRole('button', { name: '退勤を記録', exact: true }).click()
  await expect(page.locator('.clock-front')).toContainText('勤務を確認')
  await expect(page.locator('.clock-front')).not.toContainText('記録済み')
  await expect(page.locator('.clock-overtime')).toContainText('残業')
  expect(await geometry()).toEqual(before)
  await page.screenshot({ path: info.outputPath('home-recorded.png'), fullPage:true })
  await page.goto('/#/kintai'); await expect(page.locator('.talk')).toContainText('15日')
})

test('ホームだけで月を移り、過去月の記録なしとbotへの月引継ぎを表示する', async ({ page }) => {
  await page.goto('/')
  await page.locator('.home-period:visible').getByRole('link', { name:'前の月' }).click()
  await expect(page).toHaveURL(/#\/\?ym=2026-08$/)
  await expect(page.locator('.home-past .month')).toHaveText('2026年8月')
  await expect(page.locator('.home-day')).toHaveCount(0)
  await expect(page.locator('.flip')).toHaveCount(0)
  await expect(page.locator('.home-bots')).toContainText('8月の勤務記録はありません')
  await page.locator((page.viewportSize()?.width ?? 0) >= 900 ? '.desktop-sidebar [data-bot="kintai"]' : '.home-bots [data-bot="kintai"]').click()
  await expect(page).toHaveURL(/#\/kintai\?ym=2026-08$/)
  await expect(page.locator('.talk')).toContainText('8月のサンプル記録はありません')
  await expect(page.locator('.month-step')).toHaveCount(0)
  if ((page.viewportSize()?.width ?? 0) >= 900) await expect(page.locator('.desktop-sidebar-top .app-name')).toHaveText('出面帳')
  await page.locator('main .back').click()
  await expect(page).toHaveURL(/#\/\?ym=2026-08$/)
  for (const id of ['keihi', 'seikyu', 'shiharai', 'shime', 'uriage']) {
    await page.goto(`/#/${id}?ym=2026-08`)
    await expect(page.locator('.talk')).toContainText('8月のサンプル記録はありません')
    await expect(page.locator('.bot-bar')).toHaveCount(0)
    await expect(page.locator('.month-step')).toHaveCount(0)
    if ((page.viewportSize()?.width ?? 0) >= 900) await expect(page.locator('.desktop-sidebar-top .app-name')).toHaveText('出面帳')
  }
  await page.goto('/#/search?ym=2026-08')
  await page.getByLabel('現場・取引先・支払先など').fill('桜町')
  await expect(page.locator('#search-results')).toContainText('この月のサンプル記録はありません')
  await page.locator((page.viewportSize()?.width ?? 0) >= 900 ? '.sidebar-photo' : 'main [data-action="photo"]').click()
  await expect(page.locator('#edit-dialog')).not.toBeVisible()
  await page.goto('/#/?ym=2026-08')
  await page.locator('.home-period').getByRole('link', { name:'次の月' }).click()
  await expect(page.locator('.home-period:visible .home-day')).toBeVisible()
  await expect(page).toHaveURL(/#\/$/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('裏面の日付から月を選び、月選択ではカードが返らない', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '今月の足あと（働いた日と稼ぎ）を見る' }).click()
  const back = page.locator('.ura')
  await expect(back).toBeVisible()
  await back.locator('.home-day').click()
  await expect(back).toBeVisible()
  await back.getByRole('link', { name: '前の月' }).click()
  await expect(page).toHaveURL(/#\/\?ym=2026-08$/)
  await expect(page.locator('.flip')).toHaveCount(0)
})

test('狭いスマホでも表裏とカレンダーの寸法を保つ', async ({ page }) => {
  await page.setViewportSize({ width:320, height:740 })
  await page.goto('/')
  await expect(page.locator('.home-clock .flip-inner')).toHaveCSS('height', '160px')
  await page.getByRole('button', { name:'今月の足あと（働いた日と稼ぎ）を見る' }).click()
  await expect(page.locator('.ura .cal i.unworked')).toHaveCount(16)
  await expect(page.locator('.home-clock .flip-inner')).toHaveCSS('height', '160px')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('6つの画面・メニュー・狭い画面でも横にはみ出さない', async ({ page }, info) => {
  for (const [id, name] of [['kintai', 'きんたい'], ['keihi', 'けいひ'], ['seikyu', 'せいきゅう'], ['shiharai', 'しはらい'], ['shime', 'しめ'], ['uriage', 'うりあげ']]) {
    await page.goto(`/#/${id}`); await expect(page.locator('main h1')).toHaveText(name!)
    await page.evaluate(() => document.fonts.ready)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: `${name}のメニュー` }).click()
    await expect(page.locator('#bot-actions')).toBeVisible()
    await page.keyboard.press('Escape'); await expect(page.locator('#bot-actions')).not.toBeVisible()
    await expect(page.getByRole('button', { name: `${name}のメニュー` })).toBeFocused()
    if (id === 'seikyu') await page.screenshot({ path: info.outputPath('invoices.png'), fullPage: true })
  }
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/#/seikyu/invoice-1'); await page.evaluate(() => document.fonts.ready)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('経費・支払・請求を確認して月を締め、再開する', async ({ page }) => {
  await page.goto('/#/shime'); await expect(page.getByRole('button', { name: '9月を締める' })).toBeDisabled()
  await page.goto('/#/keihi/expense-1'); await page.getByRole('button', { name: 'この内容で確定する' }).click()
  await page.goto('/#/seikyu/invoice-1'); await page.getByRole('button', { name: 'この内容で発行する' }).click()
  await expect(page.locator('.talk')).toContainText('発行しました')
  await page.goto('/#/shiharai'); await page.getByRole('button', { name: '支払明細を確定', exact: true }).click()
  await page.goto('/#/shime'); await page.getByRole('button', { name: '9月を締める' }).click()
  await page.reload(); await expect(page.locator('.talk')).toContainText('9月を締めました')
  await page.goto('/#/kintai'); await expect(page.getByRole('button', { name: '勤務を追加' })).toBeDisabled()
  await page.goto('/#/shime'); await page.getByRole('button', { name: '締めを取り消す' }).click()
  await expect(page.getByRole('button', { name: '9月を締める' })).toBeEnabled()
})

test('写真と経費をブラウザ内に保存し、リセットする', async ({ page }) => {
  await page.goto('/')
  const image = await page.evaluate(() => { const c = document.createElement('canvas'); c.width = c.height = 10; c.getContext('2d')!.fillRect(0, 0, 10, 10); return c.toDataURL().split(',')[1]! })
  await page.getByRole('button', { name: 'レシートを追加する' }).click()
  await page.locator('#photo-input').setInputFiles({ name: 'sample.png', mimeType: 'image/png', buffer: Buffer.from(image, 'base64') })
  await expect(page.locator('.upload-preview')).toBeVisible()
  await page.getByLabel('支払先').fill('写真の確認店')
  await page.getByRole('button', { name: '経費に追加' }).click()
  await expect(page.locator('.shot')).toBeVisible(); await page.reload()
  await expect(page.locator('.talk')).toContainText('写真の確認店')
  await expect(page.locator('.shot')).toHaveAttribute('src', /^data:image\/jpeg;base64,/)
  await page.evaluate(() => localStorage.setItem('another-app', 'keep'))
  await page.goto('/#/app'); await page.getByRole('button', { name: 'デモをリセット' }).click()
  await page.getByRole('button', { name: 'リセットする', exact: true }).click()
  await expect(page).toHaveURL(/#\/$/)
  expect(await page.evaluate(() => localStorage.getItem('another-app'))).toBe('keep')
  await page.goto('/#/search'); await page.getByLabel('現場・取引先・支払先など').fill('写真の確認店')
  await expect(page.locator('#search-results')).toContainText('0件')
})

test('設定保存・入力のエスケープ・検索・CSV', async ({ page }) => {
  await page.goto('/#/app')
  await page.getByLabel('暗い', { exact: true }).check(); await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByLabel('表示名').fill('<img src=x onerror=alert(1)>')
  await page.getByRole('button', { name: '名前を保存' }).click()
  await expect(page.locator('img[src=x]')).toHaveCount(0)
  await page.getByLabel('けいひ', { exact: true }).check()
  await page.goto('/'); await expect(page.locator('.home-bots .row').first()).toHaveAttribute('data-bot', 'keihi')
  await page.goto('/#/search'); await page.getByLabel('現場・取引先・支払先など').fill('桜町')
  expect(await page.locator('.search-result').count()).toBeGreaterThan(0)
  await page.goto('/#/uriage')
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'サンプルCSV' }).click()
  expect((await download).suggestedFilename()).toBe('dedura-demo-sales-2026-09.csv')
})

test('通信を切っても操作でき、保存不可の場合も体験できる', async ({ page, context }) => {
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('Full', 'QuotaExceededError') } })
  await page.goto('/'); await page.evaluate(() => document.fonts.ready)
  await context.setOffline(true)
  await page.getByRole('button', { name: '出勤', exact: true }).click()
  await expect(page.locator('.home-clock .live')).toBeVisible()
  await expect(page.locator('#toast')).toContainText('保存できません')
})
